services:
  training:
    build: .
    volumes:
      - .:/app
    entrypoint: ["python3", "training/train.py"]
    container_name: edu-llm-trainer

  ui:
    build: .
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    container_name: edu-llm-ui
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
